// autogenerated from genswiftcolors --in Example/Assets.xcassets --out Example/Colors.swift

import UIKit

extension UIColor {
	
	static var biv: UIColor { return UIColor(named: #function)! }
	static var g: UIColor { return UIColor(named: #function)! }
	static var roy: UIColor { return UIColor(named: #function)! }
}
