// autogenerated from genswiftfonts --in Example/Fonts --out Example/Fonts.swift

import UIKit

extension UIFont {
	
	static func fontMarathon(of size: CGFloat) { return UIFont(name: "fontName", size: size) }
	static func fontMarathonII(of size: CGFloat) { return UIFont(name: "fontName", size: size) }
}
