// autogenerated from genswiftfonts --in Example/Fonts --out Example/Fonts.swift

import UIKit

extension UIFont {
	
	static func fontMarathon(ofSize size: CGFloat) -> UIFont { return UIFont(name: "Marathon", size: size)! }
	static func fontMarathonII(ofSize size: CGFloat) -> UIFont { return UIFont(name: "MarathonII", size: size)! }
}
