// autogenerated from genswiftnibs --in Example/Base.lproj --out Example/Nibs.swift

import UIKit
import ExtraKit

let nibView = NibDescription(nibName: "View", ownerClass: NSObject.self, topLevelObjectClass: UIView.self)
