// autogenerated from genswiftstoryboards --in Example/Base.lproj --out Example/Storyboards.swift

import UIKit
import ExtraKit

struct StoryboardMain {
	
	struct Howdy: StoryboardScene {
		typealias StoryboardClass = ViewController
		let segueShowTable  = "showTable"
		let identifier = ("Howdy", "Main")
	}
	let howdy = Howdy()
	
}
let storyboardMain = StoryboardMain()

