// autogenerated from genswiftstoryboards --in Example/Base.lproj --out Example/Storyboards.swift

import UIKit
import ExtraKit

enum StoryboardMain {
	
	struct Howdy: StoryboardScene {
		typealias StoryboardClass = ViewController
		enum Segue: String, StoryboardSceneSegue {
			case showTable
		}
		let identifier = ("Howdy", "Main")
	}
}

