// autogenerated from genswiftstrings --in Example/en.lproj/Localizable.stringsdict --out Example/StringsDict.swift

import UIKit

extension String {
	
	static var things: String { return #function }
}
