// autogenerated from genswiftstrings --in Example/en.lproj/Localizable.strings --out Example/Strings.swift

import UIKit

extension String {
	
	static var hello: String { return #function.localized() }
}
