#!/usr/bin/env swift

import Foundation

func generateStringsSourceFile(stringsPath: String, _ outputPath: String)
{
	let tmpPath = "/var/tmp/strings.plist"
	system("plutil -convert binary1 \(stringsPath) -o \(tmpPath)")
	guard let stringsDict = NSDictionary(contentsOfFile: tmpPath) else { return }
	
	var outputString = "// autogenerated by genswiftstrings.swift\n\n"
	outputString += "enum Strings: String\n{\n"

	stringsDict.allKeys.forEach {
		outputString += "\tcase \($0)\n"
	}
	outputString += "\n\tvar localized: String {\n\t\treturn NSLocalizedString(self.rawValue, comment: \"\")\n\t}\n}\n"
	try! outputString.writeToFile(outputPath, atomically: true, encoding: NSUTF8StringEncoding)
}

generateStringsSourceFile(Process.arguments[1],Process.arguments[2])
