import Foundation
import Utility

func main() {
	var outputPath: String!
	var assetsPath: String!

	let arguments = Array(CommandLine.arguments.dropFirst())

	let parser = ArgumentParser(
		usage: "genswiftcolors --xcassets <xcassets path> --src <swift output file path>"
	, 	overview: "This tool generates UIColor's from .xcasset named colors"
	)

	let xcassets = parser.add(option: "--xcassets", shortName: nil, kind: String.self, usage: nil, completion: nil)
	let src = parser.add(option: "--src", shortName: nil, kind: String.self, usage: nil, completion: nil)

	do {
		let result = try parser.parse(arguments)
		assetsPath = result.get(xcassets)
		outputPath = result.get(src)
	} catch {
		print(error)
	}

	autogeneratedLine()
	line("import UIKit")
	line()
	line("extension UIColor {")
	line()
	findFolders(extension: "colorset", in: assetsPath).sorted { $0 < $1 }.forEach {
		colorItem($0)
	}
	line("}")

	output(to: outputPath)
}

func colorItem(_ color: String) {
	if let color = URL(string: color)?.deletingPathExtension().lastPathComponent {
		outputString.addLine("\tstatic var \(color): UIColor { return UIColor(named: #function)! }")
	}
}

main()
