import Foundation
import Utility

func main() {
	var assetsPath: String!
	var outputPath: String!

	let arguments = Array(CommandLine.arguments.dropFirst())

	let parser = ArgumentParser(
		usage: "genswiftcolors --xcassets <xcassets path> --src <swift output file path>"
	, 	overview: "This tool generates UIColor's from .xcasset named colors"
	)

	let xcassetsOpt = parser.add(option: "--xcassets", shortName: nil, kind: String.self, usage: "path to xcassets", completion: nil)
	let srcOpt = parser.add(option: "--src", shortName: nil, kind: String.self, usage: "path to output swift source file", completion: nil)

	do {
		let result = try parser.parse(arguments)
		assetsPath = result.get(xcassetsOpt)
		outputPath = result.get(srcOpt)
	} catch {
		print(error)
	}

	autogeneratedLine()
	line("import UIKit")
	line()
	line("extension UIColor {")
	line()
	findFolders(extension: "colorset", in: assetsPath).sorted { $0.lastPathComponent < $1.lastPathComponent }.forEach {
		lineColor($0)
	}
	line("}")

	output(to: outputPath)
}

func lineColor(_ url: Foundation.URL) {
	let color = url.deletingPathExtension().lastPathComponent
	outputString.addLine("\tstatic var \(color): UIColor { return UIColor(named: #function)! }")
}

main()
