#!/usr/bin/env xcrun --sdk macosx swift

import Foundation
import Cocoa

var outputString = "// autogenerated by genswiftfonts.swift\n\nimport Foundation\nimport ExtraKit\n\n"

let regex = try? NSRegularExpression(pattern: "[-\\s]")

extension String {
	func enumName() -> String {
		return regex?.stringByReplacingMatches(in: self, range: NSRange(location: 0, length: characters.count), withTemplate: "").uncapitalized() ?? ""
	}
	func uncapitalized() -> String {
		return replacingCharacters(in: startIndex..<index(startIndex, offsetBy:1), with: self[startIndex...startIndex].lowercased())
	}
}

func generateFontEnum(_ path: String) {
	if let dataProvider = CGDataProvider(filename: UnsafePointer((path as NSString).utf8String!)) {
#if swift(>=4.0)
		let cgFont = CGFont(dataProvider)!
#else
		let cgFont = CGFont(dataProvider)
#endif
		let font = CTFontCreateWithGraphicsFont(cgFont, 10, nil, nil) as NSFont
		let fontName = font.fontName
		let enumName = fontName.enumName()
		outputString += "\tcase \(enumName)"
		outputString += " = \"\(fontName)\""
		outputString += "\n"
	}
}

let outputPath = CommandLine.arguments[1]
let enumName = CommandLine.arguments[2]
let fontDir = CommandLine.arguments[3]
let infoPlist = CommandLine.arguments[4]

outputString += "/**\n"
outputString += "\tGenerated from UIAppFonts in Info.plist and NSFont.fontName.\n"
outputString += "\tUsage: \(enumName).<font>.font(size: <size>)\n"
outputString += "*/\n"

if let appFonts = (NSDictionary(contentsOfFile: infoPlist) as? [String: Any])?["UIAppFonts"] as? [String] {
	outputString += "enum \(enumName): String, FontRepresentable {\n\n"
	appFonts.forEach {
		generateFontEnum("\(fontDir)/\($0)")
	}
	outputString += "}\n"
}

try? outputString.write(toFile:outputPath, atomically: true, encoding: String.Encoding.utf8)
